language: php
sudo: false

php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

os:
  - linux

before_script:
  - wget http://browscap.org/stream?q=Full_PHP_BrowsCapINI -O /tmp/browscap.ini
  - composer self-update
  - composer install -o --prefer-source
  - cp /tmp/browscap.ini resources/browscap.ini

script:
  - php -d browscap=resources/browscap.ini vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --colors --verbose
  - php vendor/bin/phpcs --standard=psr2 -pn src tests

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

