language: php

php:
  - 5.3.3
  - 5.3
  - 5.4
  - 5.5
  - 5.6

before_script:
  - if [ "`phpenv version-name`" != "hhvm" ]; then echo 'browscap = "`echo ${TRAVIS_BUILD_DIR}`/`echo ${TRAVIS_REPO_SLUG}`/tests/data/full_php_browscap.ini"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi
  - composer self-update
  - composer install --dev --prefer-source

script:
  - phpunit --coverage-text --coverage-clover=coverage.clover --colors --verbose

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

