language: php
sudo: false

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

cache:
  directories:
  - $TRAVIS_BUILD_DIR/resources

before_script:
  - .travis-scripts/cache-browscap.sh
  - travis_retry composer self-update
  - travis_retry composer install -o --prefer-source

script:
  - php -d browscap=$TRAVIS_BUILD_DIR/resources/browscap.ini vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover --colors --verbose

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover

