name: CI
on: [push]
jobs:
  test:
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['7.1','7.2','7.3','7.4', '8.0']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP for 7.1/7.2
        if: ${{ matrix.php-versions == '7.1' || matrix.php-versions == '7.2' }}
        uses: shivammathur/setup-php@v2
        env:
          fail-fast: true
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, log_errors=1
          coverage: pcov
          tools: composer:v2, phpunit:7.5.20

      - name: Setup PHP above 7.2
        if: ${{ matrix.php-versions == '7.3' || matrix.php-versions == '7.4' || matrix.php-versions == '8.0' }}
        uses: shivammathur/setup-php@v2
        env:
          fail-fast: true
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, intl
          ini-values: post_max_size=256M, log_errors=1
          coverage: pcov
          tools: composer:v2, phpunit:9.5


      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: composer install

      - name: Test with coverage
        if: ${{ matrix.php-versions == '7.3' || matrix.php-versions == '7.4' || matrix.php-versions == '8.0' }}
        run: phpunit -c phpunit.xml.dist --colors --verbose --exclude-group compare --coverage-text --coverage-clover=coverage.clover

      - name: Test without coverage for 7.1/7.2
        if: ${{ matrix.php-versions == '7.1' || matrix.php-versions == '7.2' }}
        run: phpunit -c phpunit.xml.dist --colors --verbose --exclude-group compare

      - name: Composer validate
        run: |
          composer validate --strict
          composer normalize --dry-run

  linting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        env:
          fail-fast: true
        with:
          php-version: 7.4
          extensions: mbstring, intl
          ini-values: post_max_size=768M, log_errors=1
          coverage: pcov
          tools: composer:v2

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.composer/cache/files
          key: dependencies-composer-${{ hashFiles('composer.json') }}

      - name: Install dependencies
        run: composer install

      - name: Check coding style
        env:
          COMPOSER_FLAGS: ""
          PHP_CS_FIXER_IGNORE_ENV: true
        run: vendor/bin/php-cs-fixer fix --dry-run -vv

      - name: Static code analysis
        env:
          COMPOSER_FLAGS: ""
        run: vendor/bin/phpstan analyse -l max -c phpstan.neon --autoload-file=vendor/autoload.php --memory-limit=768M --no-progress src tests

